
package com.revature.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-04-08T12:57:57.219-04:00
 * Generated source version: 3.3.0
 *
 */
public final class UpdateTicket_UpdateTicketImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.revature.com/", "UpdateTicketImplService");

    private UpdateTicket_UpdateTicketImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UpdateTicketImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        UpdateTicketImplService ss = new UpdateTicketImplService(wsdlURL, SERVICE_NAME);
        UpdateTicket port = ss.getUpdateTicketImplPort();

        {
        System.out.println("Invoking updateTicket...");
        com.revature.ws.Ticket _updateTicket_arg0 = new com.revature.ws.Ticket();
        port.updateTicket(_updateTicket_arg0);


        }

        System.exit(0);
    }

}
