package com.revature.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-04-05T23:34:21.111-04:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://ws.revature.com/", name = "UpdateOos")
@XmlSeeAlso({ObjectFactory.class})
public interface UpdateOos {

    @WebMethod
    @RequestWrapper(localName = "roomOutofService", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.RoomOutofService")
    @ResponseWrapper(localName = "roomOutofServiceResponse", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.RoomOutofServiceResponse")
    public void roomOutofService(
        @WebParam(name = "arg0", targetNamespace = "")
        com.revature.ws.Room arg0
    );

    @WebMethod
    @RequestWrapper(localName = "roomInService", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.RoomInService")
    @ResponseWrapper(localName = "roomInServiceResponse", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.RoomInServiceResponse")
    public void roomInService(
        @WebParam(name = "arg0", targetNamespace = "")
        com.revature.ws.Room arg0
    );
}
