package com.revature.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-04-08T12:57:56.950-04:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://ws.revature.com/", name = "UpdateOos")
@XmlSeeAlso({ObjectFactory.class})
public interface UpdateOos {

    @WebMethod
    @RequestWrapper(localName = "changeOutofService", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.ChangeOutofService")
    @ResponseWrapper(localName = "changeOutofServiceResponse", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.ChangeOutofServiceResponse")
    public void changeOutofService(
        @WebParam(name = "arg0", targetNamespace = "")
        com.revature.ws.Room arg0
    );
}
